In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
input_data_folder = "../data/raw/"
raw_data_file = f"{input_data_folder}/aphis_state_year_data.csv"
pathogen_df = pd.read_csv(raw_data_file)
pathogen_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11810 entries, 0 to 11809
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sample_year             11810 non-null  object
 1   sample_month_number     11810 non-null  object
 2   sample_month            11810 non-null  object
 3   state_code              11810 non-null  object
 4   sampling_county         11582 non-null  object
 5   varroa_per_100_bees     11711 non-null  object
 6   million_spores_per_bee  11711 non-null  object
 7   abpv                    11270 non-null  object
 8   abpv_percentile         1550 non-null   object
 9   amsv1                   2372 non-null   object
 10  amsv1_percentile        183 non-null    object
 11  cbpv                    11061 non-null  object
 12  cbpv_percentile         1128 non-null   object
 13  dwv                     11419 non-null  object
 14  dwv_percentile          7439 non-null   object
 15  dwv-b                   7511 non-null   object
 16  dwv-b_percentile        6651 non-null   object
 17  iapv                    11352 non-null  object
 18  iapv_percentile         1969 non-null   object
 19  kbv                     10625 non-null  object
 20  kbv_percentile          366 non-null    object
 21  lsv2                    9521 non-null   object
 22  lsv2_percentile         3077 non-null   object
 23  sbpv                    9114 non-null   object
 24  sbpv_percentile         1 non-null      object
 25  mkv                     5029 non-null   object
 26  mkv_percentile          20 non-null     object
 27  pesticides              3656 non-null   object
dtypes: object(28)
memory usage: 2.5+ MB

In [3]:
pathogen_df.drop_duplicates(inplace=True)
pathogen_df.info()
pathogen_df.keys()

<class 'pandas.core.frame.DataFrame'>
Index: 11791 entries, 0 to 11809
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sample_year             11791 non-null  object
 1   sample_month_number     11791 non-null  object
 2   sample_month            11791 non-null  object
 3   state_code              11791 non-null  object
 4   sampling_county         11565 non-null  object
 5   varroa_per_100_bees     11694 non-null  object
 6   million_spores_per_bee  11694 non-null  object
 7   abpv                    11256 non-null  object
 8   abpv_percentile         1550 non-null   object
 9   amsv1                   2370 non-null   object
 10  amsv1_percentile        183 non-null    object
 11  cbpv                    11046 non-null  object
 12  cbpv_percentile         1128 non-null   object
 13  dwv                     11404 non-null  object
 14  dwv_percentile          7439 non-null   object
 15  dwv-b                   7499 non-null   object
 16  dwv-b_percentile        6650 non-null   object
 17  iapv                    11337 non-null  object
 18  iapv_percentile         1969 non-null   object
 19  kbv                     10611 non-null  object
 20  kbv_percentile          366 non-null    object
 21  lsv2                    9509 non-null   object
 22  lsv2_percentile         3076 non-null   object
 23  sbpv                    9104 non-null   object
 24  sbpv_percentile         1 non-null      object
 25  mkv                     5022 non-null   object
 26  mkv_percentile          20 non-null     object
 27  pesticides              3656 non-null   object
dtypes: object(28)
memory usage: 2.6+ MB

Index(['sample_year', 'sample_month_number', 'sample_month', 'state_code',
       'sampling_county', 'varroa_per_100_bees', 'million_spores_per_bee',
       'abpv', 'abpv_percentile', 'amsv1', 'amsv1_percentile', 'cbpv',
       'cbpv_percentile', 'dwv', 'dwv_percentile', 'dwv-b', 'dwv-b_percentile',
       'iapv', 'iapv_percentile', 'kbv', 'kbv_percentile', 'lsv2',
       'lsv2_percentile', 'sbpv', 'sbpv_percentile', 'mkv', 'mkv_percentile',
       'pesticides'],
      dtype='object')

In [4]:
columns_to_drop = ['abpv_percentile', 'amsv1_percentile', 'cbpv_percentile', 'dwv_percentile','dwv-b_percentile',
                   'iapv_percentile','kbv_percentile', 'lsv2_percentile','sbpv_percentile', 'mkv_percentile','pesticides']
pathogen_new = pathogen_df.drop(columns=columns_to_drop, axis=1)

In [5]:
pathogen_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11791 entries, 0 to 11809
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sample_year             11791 non-null  object
 1   sample_month_number     11791 non-null  object
 2   sample_month            11791 non-null  object
 3   state_code              11791 non-null  object
 4   sampling_county         11565 non-null  object
 5   varroa_per_100_bees     11694 non-null  object
 6   million_spores_per_bee  11694 non-null  object
 7   abpv                    11256 non-null  object
 8   amsv1                   2370 non-null   object
 9   cbpv                    11046 non-null  object
 10  dwv                     11404 non-null  object
 11  dwv-b                   7499 non-null   object
 12  iapv                    11337 non-null  object
 13  kbv                     10611 non-null  object
 14  lsv2                    9509 non-null   object
 15  sbpv                    9104 non-null   object
 16  mkv                     5022 non-null   object
dtypes: object(17)
memory usage: 1.6+ MB

We are dropping few of the virus sampling data as their prevelance is very less

In [6]:
columns_to_drop = ['mkv','amsv1','sbpv','dwv-b']
pathogen_new = pathogen_new.drop(columns=columns_to_drop, axis=1)

In [7]:
pathogen_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11791 entries, 0 to 11809
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sample_year             11791 non-null  object
 1   sample_month_number     11791 non-null  object
 2   sample_month            11791 non-null  object
 3   state_code              11791 non-null  object
 4   sampling_county         11565 non-null  object
 5   varroa_per_100_bees     11694 non-null  object
 6   million_spores_per_bee  11694 non-null  object
 7   abpv                    11256 non-null  object
 8   cbpv                    11046 non-null  object
 9   dwv                     11404 non-null  object
 10  iapv                    11337 non-null  object
 11  kbv                     10611 non-null  object
 12  lsv2                    9509 non-null   object
dtypes: object(13)
memory usage: 1.3+ MB

Replace + to 1 and - to 0

In [9]:
pathogen_new.replace({'+': 1, '-': 0}, inplace=True)
pathogen_new['abpv'].value_counts()

abpv
0                                  9382
1                                  1873
Acute Bee Paralysis Virus (+/-)       1
Name: count, dtype: int64

In [10]:
pathogen_new.drop(columns=['sample_month'], axis=1, inplace=True)

In [11]:
pathogen_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11791 entries, 0 to 11809
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sample_year             11791 non-null  object
 1   sample_month_number     11791 non-null  object
 2   state_code              11791 non-null  object
 3   sampling_county         11565 non-null  object
 4   varroa_per_100_bees     11694 non-null  object
 5   million_spores_per_bee  11694 non-null  object
 6   abpv                    11256 non-null  object
 7   cbpv                    11046 non-null  object
 8   dwv                     11404 non-null  object
 9   iapv                    11337 non-null  object
 10  kbv                     10611 non-null  object
 11  lsv2                    9509 non-null   object
dtypes: object(12)
memory usage: 1.2+ MB

In [12]:
pathogen_new = pathogen_new.drop(pathogen_new.iloc[0].name)

In [13]:
pathogen_new["sample_year"] = pathogen_new["sample_year"].astype('Int64')
pathogen_new["sample_month_number"] = pathogen_new["sample_month_number"].astype('Int64')
pathogen_new["varroa_per_100_bees"] = pathogen_new["varroa_per_100_bees"].astype('Float64')
pathogen_new["million_spores_per_bee"] = pathogen_new["million_spores_per_bee"].astype('Float64')
pathogen_new["abpv"] = pathogen_new["abpv"].astype('Int64')
pathogen_new["cbpv"] = pathogen_new["cbpv"].astype('Int64')
pathogen_new["dwv"] = pathogen_new["dwv"].astype('Int64')
pathogen_new["iapv"] = pathogen_new["iapv"].astype('Int64')
pathogen_new["kbv"] = pathogen_new["kbv"].astype('Int64')
pathogen_new["lsv2"] = pathogen_new["lsv2"].astype('Int64')

In [14]:
pathogen_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11790 entries, 1 to 11809
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sample_year             11790 non-null  Int64
 1   sample_month_number     11790 non-null  Int64
 2   state_code              11790 non-null  object
 3   sampling_county         11564 non-null  object
 4   varroa_per_100_bees     11693 non-null  Float64
 5   million_spores_per_bee  11693 non-null  Float64
 6   abpv                    11255 non-null  Int64
 7   cbpv                    11045 non-null  Int64
 8   dwv                     11403 non-null  Int64
 9   iapv                    11336 non-null  Int64
 10  kbv                     10610 non-null  Int64
 11  lsv2                    9508 non-null   Int64
dtypes: Float64(2), Int64(8), object(2)
memory usage: 1.3+ MB

In [15]:
pathogen_new.head()

,sample_year,sample_month_number,state_code,sampling_county,varroa_per_100_bees,million_spores_per_bee,abpv,cbpv,dwv,iapv,kbv,lsv2
1,2009,7,HI,Hawaii,2.41,4.18,<NA>,0,0,0,0,<NA>
2,2009,7,HI,Honolulu,3.46,0.03,<NA>,0,1,0,0,<NA>
3,2009,7,HI,Honolulu,11.48,0.03,<NA>,0,0,0,0,<NA>
4,2009,7,HI,Honolulu,14.0,0.08,<NA>,0,1,0,1,<NA>
5,2009,7,HI,Honolulu,1.15,0.03,<NA>,0,1,0,0,<NA>

In [16]:
pathogen_new.to_csv("../data/processed/pathogen_data_cleaned.csv", index=False)

#### State-wise distribution of data every year

In [17]:
for year in range(2009,2024):
    print(f"Year: {year}")
    print(pathogen_new[pathogen_new["sample_year"] == year]["state_code"].value_counts())
    print("\n")

Year: 2009
state_code
CA    12
HI     7
Name: count, dtype: int64


Year: 2010
state_code
CA    35
PA    25
IN    25
GA    25
AL    25
SD    25
MI    25
FL    24
NY    24
TX    22
TN    16
HI    14
WA     8
Name: count, dtype: int64


Year: 2011
state_code
CA    57
HI    29
GA    26
NE    25
SD    25
IL    25
MI    25
NC    25
IN    25
FL    25
PA    25
UT    25
WI    25
WV    25
ND    25
AR    25
AL    25
TX    24
NY    23
NJ    21
LA    21
TN    21
CO    19
MD    19
WA    17
VA    16
IA    11
MT    10
ID     6
NM     6
OH     5
NH     3
SC     1
Name: count, dtype: int64


Year: 2012
state_code
CA    45
FL    42
ID    29
NJ    28
VA    25
MN    25
AR    24
ND    24
MA    24
MI    24
SD    24
OH    24
AL    24
WV    24
GA    24
SC    23
NY    22
NH    22
HI    20
NM    18
MD    18
IA    18
IN    17
MT    15
DE    15
LA    15
IL    15
TX    14
TN    13
WI    13
PA    11
CO     9
UT     8
OK     7
NC     6
Name: count, dtype: int64


Year: 2013
state_code
CA    44
TN    41
MN    36
UT    35
IL    33
WI    31
PA    31
TX    31
IN    31
IA    26
HI    26
WV    24
AR    24
GA    24
NJ    24
MI    24
ND    24
NE    24
MT    24
SC    24
NY    23
OH    23
FL    21
VA    20
OR    20
MD    18
OK    17
CO    16
AL    13
LA    12
SD    12
NC     7
MS     1
Name: count, dtype: int64


Year: 2014
state_code
CA    48
GU    34
SD    27
FL    25
SC    24
IL    24
IN    24
PR    24
VA    24
AR    24
GA    23
OR    23
PA    23
NY    23
ND    22
MI    21
NV    21
OH    20
MN    18
TX    18
MD    18
IA    18
HI    16
UT    13
AL    11
TN     9
MT     8
CT     7
NC     3
NJ     3
Name: count, dtype: int64


Year: 2015
state_code
CA    43
SD    32
MT    30
NJ    30
AL    27
MI    27
NY    25
VT    24
NM    24
VA    24
PR    24
IL    24
WV    24
CT    24
ID    24
IN    24
UT    24
PA    23
OH    23
WI    23
AR    23
TX    22
GA    21
HI    21
FL    20
MN    18
GU    15
TN    15
KY    12
NC    11
ND    10
IA     9
SC     8
MD     3
Name: count, dtype: int64


Year: 2016
state_code
CA    44
HI    35
MT    33
ND    29
AL    27
GA    27
PA    26
UT    26
LA    24
ID    24
WV    24
VT    24
NE    24
MA    24
WI    24
WA    24
CT    24
PR    24
NM    24
SD    24
NJ    24
KY    24
NY    23
TX    23
MN    22
MI    22
IL    22
NV    21
TN    21
DE    20
IA    20
CO    19
FL    18
SC    16
VA    16
OR    16
MD    14
MS    12
IN    12
GU    12
NC     4
OH     1
Name: count, dtype: int64


Year: 2017
state_code
IN    36
VA    31
CA    30
MN    28
NC    28
MI    26
TX    26
SD    24
MA    24
IL    24
NE    24
ID    24
AR    24
KS    24
WV    24
CT    24
NY    24
NM    24
PR    24
ND    24
VT    24
UT    24
TN    24
KY    24
SC    24
WA    23
GA    22
WI    22
OH    22
OR    21
AL    20
IA    20
MT    20
NV    19
FL    19
PA    19
NJ    18
CO    14
GU    13
MS    13
MO    12
MD    11
DE     4
Name: count, dtype: int64


Year: 2018
state_code
DE    46
OR    41
UT    39
MN    38
MD    37
FL    36
AL    35
PA    34
TX    32
MT    28
GA    27
CA    27
KY    25
SC    25
WI    24
ID    24
MA    24
WV    24
OK    24
ME    24
VT    24
ND    24
MI    24
DC    24
NY    24
IN    24
NE    24
LA    24
PR    24
SD    24
OH    24
IA    23
NV    22
AR    21
GU    18
CO    17
NC    16
WA    15
MO    12
VA    12
TN    11
AK    10
NJ     6
Name: count, dtype: int64


Year: 2019
state_code
CA    41
TN    29
AR    27
OR    25
AL    25
NY    24
WV    24
MI    24
ID    24
NE    24
IN    24
WI    24
MD    24
GA    24
MA    24
WA    24
MN    24
VA    24
ME    24
DC    24
UT    24
KY    24
TX    24
VT    23
SC    23
DE    23
NV    21
FL    21
PA    20
HI    19
SD    19
MT    17
PR    15
GU    14
ND     7
AK     6
OH     2
Name: count, dtype: int64


Year: 2020
state_code
CA    40
SD    29
MT    27
SC    26
ND    25
LA    24
WV    24
DE    24
MI    24
VT    24
NE    24
MN    24
AR    24
NY    24
WI    24
VA    24
GA    24
MA    24
TX    24
MD    23
OR    23
IL    23
GU    23
AL    23
KY    23
PA    22
NV    22
IN    22
ID    20
DC    19
FL    19
UT    15
AK    10
TN     5
HI     5
PR     1
Name: count, dtype: int64


Year: 2021
state_code
CA    57
ND    36
FL    29
MT    27
ID    26
IN    25
KY    25
MN    24
SD    24
OR    24
NE    24
VT    24
AR    24
WV    24
NY    24
GA    24
MD    24
VA    24
MI    24
ME    24
WI    24
DC    24
PA    24
MA    23
SC    23
WA    22
DE    21
AL    20
NV    19
TX    19
HI    17
UT    15
GU    14
LA    13
AK     8
CO     7
TN     4
IL     1
Name: count, dtype: int64


Year: 2022
state_code
CA    49
DC    33
DE    30
MN    29
MA    25
WV    25
KY    24
VA    24
NY    24
NE    24
ME    24
AR    24
VT    24
WI    24
GA    24
SD    24
IN    24
ID    24
SC    23
LA    23
OR    22
FL    22
MD    22
PA    22
OH    21
MT    21
TN    21
WA    19
CO    19
NV    19
TX    19
GU    18
MI    18
AL    17
ND    15
UT    13
NM    13
HI     9
NC     9
NJ     4
AK     2
Name: count, dtype: int64


Year: 2023
state_code
CA    41
SC    27
ND    26
TX    25
MA    24
SD    24
VA    24
ID    24
IN    24
DC    24
PA    24
WV    24
MD    24
AR    24
ME    24
NY    24
DE    24
UT    24
NE    24
WI    24
AK    24
VT    24
MN    23
CO    23
KY    23
TN    23
NJ    22
NM    22
AL    22
GU    22
FL    20
MT    19
NV    18
OK    13
LA    12
MI    12
GA    12
OH    11
NC    10
OR     1
Name: count, dtype: int64

#### Dropping rows older than 2015

We do not have quarterly data older than 2015 in our primary dataset of bee-colony loss.

In [18]:
pathogen_new = pathogen_new[pathogen_new["sample_year"] >= 2015].reset_index(drop=True)

In [19]:
pathogen_new.head()

,sample_year,sample_month_number,state_code,sampling_county,varroa_per_100_bees,million_spores_per_bee,abpv,cbpv,dwv,iapv,kbv,lsv2
0,2015,1,CA,NaN,2.74,1.85,1,0,1,1,0,0
1,2015,1,CA,NaN,0.66,0.9,1,0,1,0,0,1
2,2015,1,CA,Butte,0.0,0.0,0,0,1,0,0,1
3,2015,1,FL,Calhoun,1.07,0.1,0,0,1,0,0,0
4,2015,1,FL,Calhoun,0.79,0.1,0,0,1,0,0,1

In [20]:
pathogen_new.to_csv("../data/processed/pathogen_data_cleaned_2015_onwards.csv", index=False)

#### Aggregating quarterly data

To do so, let us first define a new column containing quarter information for every sample_month_number

In [21]:
month_quarter_map = {"1": "Q1", "2" : "Q1", "3": "Q1",
 "4": "Q2", "5" : "Q2", "6": "Q2",
 "7": "Q3", "8" : "Q3", "9": "Q3",
 "10": "Q4", "11" : "Q4", "12": "Q4"}

pathogen_new['sample_quarter'] = pathogen_new['sample_month_number'].astype(str).map(month_quarter_map)
last_col_name = pathogen_new.columns[-1]
last_col_data = pathogen_new.pop(last_col_name)
pathogen_new.insert(2, last_col_name, last_col_data)

In [22]:
pathogen_new.head()

,sample_year,sample_month_number,sample_quarter,state_code,sampling_county,varroa_per_100_bees,million_spores_per_bee,abpv,cbpv,dwv,iapv,kbv,lsv2
0,2015,1,Q1,CA,NaN,2.74,1.85,1,0,1,1,0,0
1,2015,1,Q1,CA,NaN,0.66,0.9,1,0,1,0,0,1
2,2015,1,Q1,CA,Butte,0.0,0.0,0,0,1,0,0,1
3,2015,1,Q1,FL,Calhoun,1.07,0.1,0,0,1,0,0,0
4,2015,1,Q1,FL,Calhoun,0.79,0.1,0,0,1,0,0,1

In [32]:
monthly_agg_df = (
    pathogen_new.groupby(["sample_year", "sample_month_number", "state_code","sample_quarter"])
    .agg(
        # Varroa Metrics
        mean_varroa=('varroa_per_100_bees', 'mean'),
        varroa_total_samples=('varroa_per_100_bees', 'count'),
        
        # Nosema Spore Metrics
        mean_spores=('million_spores_per_bee', 'mean'),
        spores_total_samples=('million_spores_per_bee', 'count'),
        
        # Virus Prevalence Metrics
        abpv_prevalence=('abpv', 'mean'),
        abpv_total_samples=('abpv', 'count'),
        cbpv_prevalence=('cbpv', 'mean'),
        cbpv_total_samples=('cbpv', 'count'),
        dwv_prevalence=('dwv', 'mean'),
        dwv_total_samples=('dwv', 'count'),
        iapv_prevalence=('iapv', 'mean'),
        iapv_total_samples=('iapv', 'count'),
        kbv_prevalence=('kbv', 'mean'),
        kbv_total_samples=('kbv', 'count'),
        lsv2_prevalence=('lsv2', 'mean'),
        lsv2_total_samples=('lsv2', 'count'),
        
        unique_counties_sampled=('sampling_county', 'nunique') 
    )
    .reset_index()
)

In [35]:
monthly_agg_df.head(50)
monthly_agg_df.to_csv("../data/processed/pathogen_data_monthly_aggregated_2015_onwards.csv", index=False)
cp_monthly_agg_df = monthly_agg_df.copy(deep=True)

In [47]:
# Define pathogen lists
pathogens = ['varroa', 'spores', 'abpv', 'cbpv', 'dwv', 'iapv', 'kbv', 'lsv2']
mean_cols = ['mean_varroa', 'mean_spores']
prev_cols = ['abpv_prevalence', 'cbpv_prevalence', 'dwv_prevalence', 'iapv_prevalence', 'kbv_prevalence', 'lsv2_prevalence']
all_measure_cols = mean_cols + prev_cols

cp_monthly_agg_df[all_measure_cols] = cp_monthly_agg_df[all_measure_cols].fillna(0)

# Calculate weighted monthly values
for pathogen in pathogens:
    if pathogen in ['varroa', 'spores']:
        measure_col = f'mean_{pathogen}'
        total_col = f'{pathogen}_total_samples'
    else:
        measure_col = f'{pathogen}_prevalence'
        total_col = f'{pathogen}_total_samples'
    
    weighted_col = f'{pathogen}_weighted_sum' 
    cp_monthly_agg_df[weighted_col] = cp_monthly_agg_df[measure_col].fillna(0) * cp_monthly_agg_df[total_col]

# Sort data for correct 'last' aggregation
cp_monthly_agg_df = cp_monthly_agg_df.sort_values(by=['sample_year', 'state_code', 'sample_month_number'])

cp_monthly_agg_df.head()

,sample_year,sample_month_number,state_code,sample_quarter,mean_varroa,varroa_total_samples,mean_spores,spores_total_samples,abpv_prevalence,abpv_total_samples,...,kbv_quarter_avg,lsv2_quarter_avg,varroa_weighted_sum,spores_weighted_sum,abpv_weighted_sum,cbpv_weighted_sum,dwv_weighted_sum,iapv_weighted_sum,kbv_weighted_sum,lsv2_weighted_sum
11,2015,4,AL,Q2,1.883333,3,0.266667,3,0.0,3,...,0.0,3.0,5.65,0.8,0.0,1.0,2.0,0.0,0.0,3.0
17,2015,5,AL,Q2,3.63,1,0.2,1,0.0,1,...,0.0,0.0,3.63,0.2,0.0,0.0,1.0,0.0,0.0,0.0
26,2015,6,AL,Q2,2.382727,11,0.104545,11,0.0,11,...,1.0,4.0,26.21,1.15,0.0,2.0,9.0,1.0,1.0,4.0
92,2015,9,AL,Q3,4.143,10,0.09,10,0.125,8,...,1.0,3.0,41.43,0.9,1.0,0.0,8.0,0.0,1.0,3.0
117,2015,10,AL,Q4,9.085,2,0.0,2,0.0,2,...,0.0,1.0,18.17,0.0,0.0,0.0,2.0,0.0,0.0,1.0

In [ ]:
# Define grouping and aggregations
group_keys = ['sample_year', 'sample_quarter', 'state_code']
agg_dict = {}

for pathogen in pathogens:
    if pathogen in ['varroa', 'spores']:
        measure_col = f'mean_{pathogen}'
        total_col = f'{pathogen}_total_samples'
    else:
        measure_col = f'{pathogen}_prevalence'
        total_col = f'{pathogen}_total_samples'
    
    weighted_col = f'{pathogen}_weighted_sum'

    # Add aggregations to dict
    agg_dict[f'{total_col}_q'] = (total_col, 'sum')
    agg_dict[f'{weighted_col}_q'] = (weighted_col, 'sum') # (was f'{quarterly_avg}_q')
    agg_dict[f'worst_month_{measure_col}'] = (measure_col, 'max')
    agg_dict[f'last_month_{measure_col}'] = (measure_col, 'last')

# Add other aggregations
agg_dict['unique_counties_sampled_q'] = ('unique_counties_sampled', 'sum')
agg_dict['last_month_in_quarter'] = ('sample_month_number', 'max')

# Perform aggregation
quarterly_df = cp_monthly_agg_df.groupby(group_keys).agg(**agg_dict).reset_index()

# Post-Aggregation Calculations (Quarterly Means)
final_columns_order = list(group_keys) # Start with grouping keys

# Lists to hold new column names for ordering
quarterly_mean_cols = []
quarterly_total_cols = []
worst_month_cols = []
last_month_cols = []

for pathogen in pathogens:
    if pathogen in ['varroa', 'spores']:
        measure_col_name = f'mean_{pathogen}'
        q_mean_col_name = f'mean_{pathogen}_q'
    else:
        measure_col_name = f'{pathogen}_prevalence'
        q_mean_col_name = f'{pathogen}_prevalence_q'

    total_col_q_name = f'{pathogen}_total_samples_q'
    
    # --- FIX 2 ---
    # Use the name that was created in the aggregation dict
    # (was '_weighted_sum_q')
    weighted_col_q_name = f'{pathogen}_weighted_sum_q' 
    worst_col_name = f'worst_month_{measure_col_name}'
    last_col_name = f'last_month_{measure_col_name}'

    # Calculate quarterly mean (weighted average)
    quarterly_df[q_mean_col_name] = quarterly_df[weighted_col_q_name] / quarterly_df[total_col_q_name]
    
    # Handle division by zero (replace NaN with 0)
    quarterly_df[q_mean_col_name] = quarterly_df[q_mean_col_name].fillna(0)

    # Add to ordered lists
    quarterly_mean_cols.append(q_mean_col_name)
    quarterly_total_cols.append(total_col_q_name)
    worst_month_cols.append(worst_col_name)
    last_month_cols.append(last_col_name)

# Define the final
final_columns_order.extend(quarterly_mean_cols)
final_columns_order.extend(quarterly_total_cols)
final_columns_order.extend(worst_month_cols)
final_columns_order.extend(last_month_cols)
final_columns_order.append('unique_counties_sampled_q')
final_columns_order.append('last_month_in_quarter')

# Keep only the relevant columns in the defined order
quarterly_df_final = quarterly_df[final_columns_order]

# Save the aggregated data
output_file_path = 'pathogen_data_quarterly_aggregated.csv'
quarterly_df_final.to_csv(output_file_path, index=False)

# Print head and info of the new dataframe
print(f"Aggregated data saved to: {output_file_path}")
print("\nQuarterly Aggregated DataFrame Head:")
print(quarterly_df_final.head())
print("\nQuarterly Aggregated DataFrame Info:")
quarterly_df_final.info()

In [44]:
quarterly_df_final.head()

,sample_year,sample_quarter,state_code,mean_varroa_q,mean_spores_q,abpv_prevalence_q,cbpv_prevalence_q,dwv_prevalence_q,iapv_prevalence_q,kbv_prevalence_q,...,last_month_mean_varroa,last_month_mean_spores,last_month_abpv_prevalence,last_month_cbpv_prevalence,last_month_dwv_prevalence,last_month_iapv_prevalence,last_month_kbv_prevalence,last_month_lsv2_prevalence,unique_counties_sampled_q,last_month_in_quarter
0,2015,Q1,CA,0.791176,2.417647,0.352941,0.176471,0.882353,0.235294,0.176471,...,0.0,1.15,0.0,0.0,1.0,0.0,0.0,1.0,6,2
1,2015,Q1,FL,0.372,0.12,0.2,0.2,0.8,0.0,0.0,...,0.372,0.12,0.2,0.2,0.8,0.0,0.0,0.6,4,1
2,2015,Q1,GU,0.126667,2.0,NaN,NaN,NaN,NaN,NaN,...,0.0,3.85,0.0,0.0,0.0,0.0,0.0,0.0,0,3
3,2015,Q1,HI,0.9,0.675,0.166667,0.166667,0.5,0.166667,0.0,...,1.24,1.266667,0.333333,0.333333,0.666667,0.333333,0.0,0.0,3,3
4,2015,Q1,TX,1.366,0.22,0.0,0.0,0.6,0.0,0.2,...,1.35,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4,3

In [48]:
quarterly_df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   sample_year                  994 non-null    Int64
 1   sample_quarter               994 non-null    object
 2   state_code                   994 non-null    object
 3   mean_varroa_q                994 non-null    Float64
 4   mean_spores_q                994 non-null    Float64
 5   abpv_prevalence_q            994 non-null    Float64
 6   cbpv_prevalence_q            994 non-null    Float64
 7   dwv_prevalence_q             994 non-null    Float64
 8   iapv_prevalence_q            994 non-null    Float64
 9   kbv_prevalence_q             994 non-null    Float64
 10  lsv2_prevalence_q            994 non-null    Float64
 11  varroa_total_samples_q       994 non-null    int64
 12  spores_total_samples_q       994 non-null    int64
 13  abpv_total_samples_q         994 non-null    int64
 14  cbpv_total_samples_q         994 non-null    int64
 15  dwv_total_samples_q          994 non-null    int64
 16  iapv_total_samples_q         994 non-null    int64
 17  kbv_total_samples_q          994 non-null    int64
 18  lsv2_total_samples_q         994 non-null    int64
 19  worst_month_mean_varroa      994 non-null    Float64
 20  worst_month_mean_spores      994 non-null    Float64
 21  worst_month_abpv_prevalence  994 non-null    Float64
 22  worst_month_cbpv_prevalence  994 non-null    Float64
 23  worst_month_dwv_prevalence   994 non-null    Float64
 24  worst_month_iapv_prevalence  994 non-null    Float64
 25  worst_month_kbv_prevalence   994 non-null    Float64
 26  worst_month_lsv2_prevalence  994 non-null    Float64
 27  last_month_mean_varroa       994 non-null    Float64
 28  last_month_mean_spores       994 non-null    Float64
 29  last_month_abpv_prevalence   994 non-null    Float64
 30  last_month_cbpv_prevalence   994 non-null    Float64
 31  last_month_dwv_prevalence    994 non-null    Float64
 32  last_month_iapv_prevalence   994 non-null    Float64
 33  last_month_kbv_prevalence    994 non-null    Float64
 34  last_month_lsv2_prevalence   994 non-null    Float64
 35  unique_counties_sampled_q    994 non-null    int64
 36  last_month_in_quarter        994 non-null    Int64
dtypes: Float64(24), Int64(2), int64(9), object(2)
memory usage: 312.7+ KB

In [67]:
quarterly_df_final[quarterly_df_final['state_code'] == 'TX'][['sample_year','sample_quarter','mean_varroa_q','worst_month_mean_varroa','last_month_mean_varroa']]

,sample_year,sample_quarter,mean_varroa_q,worst_month_mean_varroa,last_month_mean_varroa
4,2015,Q1,1.366,2.74,1.35
25,2015,Q2,1.48,3.05,3.05
54,2015,Q3,3.48,3.68,3.44
77,2015,Q4,0.46,1.91,0.0
89,2016,Q1,4.168,6.74,3.14
117,2016,Q2,1.233333,1.376,1.165
178,2016,Q4,2.582222,3.32,2.213333
190,2017,Q1,0.83,2.37,0.06
219,2017,Q2,1.445833,2.825,2.825
282,2017,Q4,2.862727,3.935,0.02
294,2018,Q1,0.045,0.045,0.045
325,2018,Q2,0.671818,0.887143,0.34
361,2018,Q3,0.954,0.954,0.954
390,2018,Q4,1.797143,2.162,0.0
400,2019,Q1,0.57,0.76,0.76
426,2019,Q2,0.2775,0.31,0.31
460,2019,Q3,4.053333,5.845,5.845
486,2019,Q4,1.242,2.235,0.12
499,2020,Q1,4.06,14.93,0.135
518,2020,Q2,1.651429,6.15,1.064
552,2020,Q3,0.17,0.17,0.0
576,2020,Q4,1.053333,2.1,0.0
586,2021,Q1,0.046667,0.046667,0.046667
612,2021,Q2,0.06,0.06,0.06
649,2021,Q3,2.658333,4.5,4.5
678,2021,Q4,2.405,3.5325,3.5325
694,2022,Q1,0.48,0.96,0.0
724,2022,Q2,0.37625,0.385,0.385
759,2022,Q3,2.41,2.41,2.41
784,2022,Q4,0.228333,0.2925,0.2
797,2023,Q1,0.718571,1.0925,1.0925
826,2023,Q2,0.6875,0.6875,0.6875
864,2023,Q3,0.786667,0.786667,0.786667
891,2023,Q4,2.604286,4.633333,1.443333
902,2024,Q1,0.741429,0.88,0.88
929,2024,Q2,0.77,0.77,0.77
964,2024,Q3,2.272,3.395,2.285
989,2024,Q4,0.815,1.23,0.8